version: '3.8'
services:
  frontend:
    image: haddejit/mern-frontend:latest
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://backend:4000
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    image: haddejit/mern-backend:latest
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://talel:talel@mongo:27017/Projet?authSource=admin
      - PORT=4000
    depends_on:
      - mongodb
    networks:
      - app-network

  mongodb:
    image: mongo:6
    container_name: mongodb
    command: mongod --bind_ip_all --auth
    environment:
      - MONGO_INITDB_ROOT_USERNAME=talel
      - MONGO_INITDB_ROOT_PASSWORD=talel
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data: {}