apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongo
        image: mongo:latest
        ports:
        - containerPort: 27018
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: "talel"
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: "talel"
